name: clang-format

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  formatting-check:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install clang-format
        run: |
          pip install clang-format
          clang-format --version

      - name: Format files
        run: ${{ github.workspace }}/scripts/format.sh ${{ github.workspace }} y

      - name: Commit changes
        if: github.event_name == 'push'
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'style: apply clang-format [skip build]'
          add: '["*.cpp", "*.cu", "*.cuh", "*.hxx"]'
